id: P90C4A964
initial_creation_type: input
source_metadata:
  title: Triṃśikāvijñaptikārikā with Sthiramati's Triṃśikāvijñaptibhāṣya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Takamichi Fukita
  contribution to GRETIL: Takamichi Fukita
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:25:19.410085'
last_modified_at: '2022-03-09T15:25:19.410098'
